cloud_filter_chain:
-   name: body_filter
    type: robot_body_filter/RobotBodyFilterPointCloud2
    params:
        frames/filtering: '$(arg tf_prefix)base_link'
        frames/output: '$(arg tf_prefix)sensor_rack/front_lidar'
        sensor/min_distance: 0.05
        sensor/max_distance: 50.0
        body_model/inflation/scale: 1.01
        body_model/inflation/padding: 0.01
        body_model/inflation/per_link/scale:
            "$(arg tf_prefix)sensor_rack::collision_top": 1.2
        filter/do_shadow_test: False
        debug/pcl/inside: True
        debug/pcl/clip: True
        debug/marker/contains: True