cloud_filter_chain:
-   name: body_filter
    type: robot_body_filter/RobotBodyFilterPointCloud2
    params:
        frames/filtering: '$(arg tf_prefix)base_link'
        frames/output: '$(arg tf_prefix)sensor_rack/front_lidar'
        sensor/min_distance: 0.05
        sensor/max_distance: 50.0
        ignored_links/contains_test: [
                "$(arg tf_prefix)front_left_wheel_link", "$(arg tf_prefix)front_right_wheel_link",
                "$(arg tf_prefix)front_middle_left_wheel_link", "$(arg tf_prefix)front_middle_right_wheel_link",
                "$(arg tf_prefix)rear_left_wheel_link", "$(arg tf_prefix)rear_right_wheel_link",
                "$(arg tf_prefix)rear_middle_left_wheel_link", "$(arg tf_prefix)rear_middle_right_wheel_link",
        ]
        body_model/inflation/scale: 1.01
        body_model/inflation/padding: 0.01
        body_model/inflation/per_link/scale:
            "$(arg tf_prefix)sensor_rack::collision_top": 1.2
        filter/do_shadow_test: False
        # Bounding sphere
        bounding_sphere/compute: True
        bounding_sphere/debug: True
        bounding_sphere/marker: True
        bounding_sphere/publish_cut_out_pointcloud: True
        # Bounding box
        bounding_box/compute: True
        bounding_box/debug: True
        bounding_box/marker: True
        bounding_box/publish_cut_out_pointcloud: True
        # Debug clouds/markers
        debug/pcl/inside: True
        debug/pcl/clip: True
        debug/pcl/shadow: True
        debug/marker/contains: True
        debug/marker/shadow: True
        debug/marker/bounding_sphere: True
        debug/marker/bounding_box: True