laser_filter:
    cloud_filter_chain:
    -   name: body_filter
        type: robot_body_filter/RobotBodyFilterPointCloud2
        params:
            frames/filtering: '$(arg tf_prefix)base_link'
            frames/output: '$(arg tf_prefix)laser/laser'
            sensor/min_distance: 0.2  # larger because of lidar rendering errors
            sensor/max_distance: 50.0
            ignored_links/bounding_sphere: ["$(arg tf_prefix)payload"]
            body_model/inflation/scale: 1.05
            body_model/inflation/padding: 0.01
            body_model/inflation/per_link/scale:
                "$(arg tf_prefix)payload": 1.1
            filter/do_shadow_test: False
            # Bounding sphere
            bounding_sphere/compute: True
            bounding_sphere/debug: True
            bounding_sphere/marker: True
            bounding_sphere/publish_cut_out_pointcloud: True
            # Bounding box
            bounding_box/compute: True
            bounding_box/debug: True
            bounding_box/marker: True
            bounding_box/publish_cut_out_pointcloud: True
            # Debug clouds/markers
            debug/pcl/inside: True
            debug/pcl/clip: True
            debug/pcl/shadow: True
            debug/marker/contains: True
            debug/marker/shadow: True
            debug/marker/bounding_sphere: True
            debug/marker/bounding_box: True

tof_back_filter:
    cloud_filter_chain:
    -   name: body_filter
        type: robot_body_filter/RobotBodyFilterPointCloud2
        params:
            frames/filtering: '$(arg tf_prefix)camera_back/back_depth'
            only_links: [
                    "$(arg tf_prefix)rear_left_upper_leg", "$(arg tf_prefix)rear_right_upper_leg",
                    "$(arg tf_prefix)rear_left_lower_leg", "$(arg tf_prefix)rear_right_lower_leg",
            ]
            body_model/inflation/padding: 0.15
            filter/do_clipping: False
            filter/do_shadow_test: False

tof_left_filter:
    cloud_filter_chain:
    -   name: body_filter
        type: robot_body_filter/RobotBodyFilterPointCloud2
        params:
            frames/filtering: '$(arg tf_prefix)camera_left/left_depth'
            only_links: [
                    "$(arg tf_prefix)rear_left_upper_leg", "$(arg tf_prefix)front_left_upper_leg",
                    "$(arg tf_prefix)rear_left_lower_leg", "$(arg tf_prefix)front_left_lower_leg",
            ]
            body_model/inflation/padding: 0.15
            filter/do_clipping: False
            filter/do_shadow_test: False

tof_right_filter:
    cloud_filter_chain:
    -   name: body_filter
        type: robot_body_filter/RobotBodyFilterPointCloud2
        params:
            frames/filtering: '$(arg tf_prefix)camera_right/right_depth'
            only_links: [
                    "$(arg tf_prefix)rear_right_upper_leg", "$(arg tf_prefix)front_right_upper_leg",
                    "$(arg tf_prefix)rear_right_lower_leg", "$(arg tf_prefix)front_right_lower_leg",
            ]
            body_model/inflation/padding: 0.15
            filter/do_clipping: False
            filter/do_shadow_test: False

tof_frontleft_filter:
    cloud_filter_chain:
    -   name: body_filter
        type: robot_body_filter/RobotBodyFilterPointCloud2
        params:
            frames/filtering: '$(arg tf_prefix)camera_frontleft/frontleft_depth'
            only_links: [
                    "$(arg tf_prefix)front_left_upper_leg", "$(arg tf_prefix)front_right_upper_leg",
                    "$(arg tf_prefix)front_left_lower_leg", "$(arg tf_prefix)front_right_lower_leg",
            ]
            body_model/inflation/padding: 0.15
            filter/do_clipping: False
            filter/do_shadow_test: False

tof_frontright_filter:
    cloud_filter_chain:
    -   name: body_filter
        type: robot_body_filter/RobotBodyFilterPointCloud2
        params:
            frames/filtering: '$(arg tf_prefix)camera_frontright/frontright_depth'
            only_links: [
                    "$(arg tf_prefix)front_left_upper_leg", "$(arg tf_prefix)front_right_upper_leg",
                    "$(arg tf_prefix)front_left_lower_leg", "$(arg tf_prefix)front_right_lower_leg",
            ]
            body_model/inflation/padding: 0.15
            filter/do_clipping: False
            filter/do_shadow_test: False

