laser_filter:
    cloud_filter_chain:
    -   name: body_filter
        type: robot_body_filter/RobotBodyFilterPointCloud2
        params:
            frames/filtering: '$(arg tf_prefix)base_link/front_laser'
            sensor/point_by_point: False
            sensor/min_distance: 0.25
            sensor/max_distance: 50.0
            body_model/inflation/scale: 1.01
            body_model/inflation/padding: 0.01
            body_model/inflation/per_link/scale:
                "$(arg tf_prefix)rotor_0": 1.05
                "$(arg tf_prefix)rotor_1": 1.05
                "$(arg tf_prefix)rotor_2": 1.05
                "$(arg tf_prefix)rotor_3": 1.05
                "$(arg tf_prefix)base_link::base_link_inertia_collision": 0.7
            ignored_links/shadow_test: [
                "$(arg tf_prefix)base_link::base_link_fixed_joint_lump__os_sensor_link_collision_7",
            ]
            filter/do_clipping: True
            filter/do_shadow_test: True
            filter/max_shadow_distance: 0.45
            # Bounding sphere
            bounding_sphere/compute: True
            bounding_sphere/debug: True
            bounding_sphere/marker: True
            bounding_sphere/publish_cut_out_pointcloud: True
            # Bounding box
            bounding_box/compute: True
            bounding_box/debug: True
            bounding_box/marker: True
            bounding_box/publish_cut_out_pointcloud: True
            # Debug clouds/markers
            debug/pcl/inside: True
            debug/pcl/clip: True
            debug/pcl/shadow: True
            debug/marker/contains: True
            debug/marker/shadow: True
            debug/marker/bounding_sphere: True
            debug/marker/bounding_box: True

rs_up_filter:
    cloud_filter_chain:
    -   name: body_filter
        type: robot_body_filter/RobotBodyFilterPointCloud2
        params:
            frames/filtering: '$(arg tf_prefix)base_link/rs_up'
            sensor/point_by_point: False
            body_model/inflation/scale: 1.01
            body_model/inflation/padding: 0.01
            only_links: ["$(arg tf_prefix)base_link::base_link_fixed_joint_lump__os_sensor_link_collision_7"]
            ignored_links/shadow_test: [
                "$(arg tf_prefix)base_link::base_link_inertia_collision",
            ]
            filter/do_clipping: False
            filter/do_shadow_test: True
            filter/max_shadow_distance: 0.15