#!/bin/bash

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

robot="$1"

dir="$script_dir"
if [ $# -gt 1 ]; then
  dir="$2"
fi

pushd "$dir" >/dev/null || exit 1

echo "Downloading BAG files to $dir" >&2

f="${robot}.bag"
if [ ! -f $f ]; then
  echo "Downloading $f" >&2
  wget "http://ptak.felk.cvut.cz/darpa-subt/data/share/rosdevday_cloud_filtering/${f}"
fi

echo "BAG files downloaded" >&2

popd || exit 1